/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangun_datar_202557201008;

/**
 *
 * @author Acer
 */
public class beranda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(beranda.class.getName());

    /**
     * Creates new form beranda
     */
    public beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnsegitiga = new javax.swing.JButton();
        btnpersegipanjang = new javax.swing.JButton();
        btnlingkaran = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnpersegi = new javax.swing.JButton();
        btntrapesium = new javax.swing.JButton();
        btnjajargenjang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("beranda");

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI BANGUN DATAR");

        btnsegitiga.setText("Segitiga");
        btnsegitiga.addActionListener(this::btnsegitigaActionPerformed);

        btnpersegipanjang.setText("Persegi Panjang");
        btnpersegipanjang.addActionListener(this::btnpersegipanjangActionPerformed);

        btnlingkaran.setText("Lingkaran");
        btnlingkaran.addActionListener(this::btnlingkaranActionPerformed);

        btnexit.setText("Exit");
        btnexit.addActionListener(this::btnexitActionPerformed);

        btnpersegi.setText("Persegi");
        btnpersegi.addActionListener(this::btnpersegiActionPerformed);

        btntrapesium.setText("Trapesium");
        btntrapesium.addActionListener(this::btntrapesiumActionPerformed);

        btnjajargenjang.setText("Jajar Genjang");
        btnjajargenjang.addActionListener(this::btnjajargenjangActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnexit)
                .addGap(35, 35, 35))
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlingkaran, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnpersegipanjang)
                    .addComponent(btnsegitiga, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnpersegi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btntrapesium, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnjajargenjang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsegitiga)
                    .addComponent(btnpersegi))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnpersegipanjang)
                    .addComponent(btntrapesium))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlingkaran)
                    .addComponent(btnjajargenjang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(btnexit)
                .addGap(20, 20, 20))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnpersegipanjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersegipanjangActionPerformed
        // TODO add your handling code here:
        new Persegipanjang().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnpersegipanjangActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnsegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsegitigaActionPerformed
        // TODO add your handling code here:
        new Segitiga().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnsegitigaActionPerformed

    private void btnlingkaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlingkaranActionPerformed
        // TODO add your handling code here:
        new Lingkaran().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlingkaranActionPerformed

    private void btnpersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpersegiActionPerformed
        // TODO add your handling code here:
        new Persegi().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnpersegiActionPerformed

    private void btntrapesiumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrapesiumActionPerformed
        // TODO add your handling code here:
        new Trapesium().setVisible(true);
        dispose();
    }//GEN-LAST:event_btntrapesiumActionPerformed

    private void btnjajargenjangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjajargenjangActionPerformed
        // TODO add your handling code here:
        new Jajar_Genjang().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnjajargenjangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new beranda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnjajargenjang;
    private javax.swing.JButton btnlingkaran;
    private javax.swing.JButton btnpersegi;
    private javax.swing.JButton btnpersegipanjang;
    private javax.swing.JButton btnsegitiga;
    private javax.swing.JButton btntrapesium;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
